### ISSUE TITLE
gzip support

### ISSUE THREAD

**Issue by eveliotc** [kevinsawicki/etag-cache#1]
Hello,

Not sure if on purpose but It seems `CacheRequest#stream` breaks gzip support for 200 and  304, I will follow up with a test demonstrating this.

Thanks!

**Comment by kevinsawicki** [comment]
Hi,

Thanks for reporting this.

I push a fix that adds handling for gzipped responses.

Can you verify it now works for you?

**Comment by eveliotc** [comment]
Works great! thanks a lot!

**Comment by kevinsawicki** [comment]
Okay, I'll do a `0.3` release with the fix now.

**Comment by eveliotc** [comment]
Hi, sorry but it seems 0.3 is still not available on maven central

**Comment by kevinsawicki** [comment]
Apologies, I pushed it to https://oss.sonatype.org but forget to promote it over to Maven Central.

I just promoted it so it should now show up in Maven Central in the new few hours.

Thanks for pointing it out!

**Comment by eveliotc** [comment]
Awesome! thanks again!
